# This is a basic workflow to help you get started with Actions

name: Verify file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  verify:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXE_WF == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run : |
            [[ -f ${{ vars.FILE_TO_CHECK }} ]] ||
            ( echo "${{ vars.FILE_TH_CHECK }} file needs to be added to ${{ github.repository }} !" && exit 1)
